version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo intall
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
#      - cd project_2/demo
#      - mvn package spring-boot:repackage
#      - mv target/demo.jar $CODEBUILD_SRC_DIR/
      - mvn install
      - echo Build completed on `date`
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/reviewapp-0.01-SNAPSHOT.jar